# Generated by Django 3.2.7 on 2021-11-24 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notetype', models.CharField(choices=[('T', 'To-Do'), ('R', 'Reminder'), ('L', 'Vocab/Learning')], default='R', max_length=1)),
                ('content', models.TextField(max_length=300)),
                ('date', models.DateField(verbose_name='Due date')),
                ('color', models.CharField(choices=[('PI', 'pink'), ('BP', 'bright pink'), ('BY', 'yellow'), ('DY', 'dark yellow'), ('BL', 'blue'), ('GR', 'green')], default='BY', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
