# Generated by Django 3.2.7 on 2021-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='homescreen',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
