# Generated by Django 3.2.7 on 2021-11-28 21:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211127_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='toDo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
    ]
