# Generated by Django 3.2.7 on 2021-11-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
