# Generated by Django 3.2.7 on 2021-12-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20211129_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('#EAEC40', 'Dandelion'), ('#FF7EB9', 'pink'), ('#F275AD', 'Cyclamen'), ('#79CBC5', 'Pearl Aqua'), ('#FFFF97', 'Canary'), ('#7AFCFF', 'blue'), ('#FBAE4A', 'Pastel Orange'), ('#F3858E', 'Tulip'), ('#B2EC5D', 'Inchworm'), ('#8D9440', 'Bright Green'), ('#FFFFFF', 'White'), ('#BEBEBE', 'Grey')], default='#F275AD', max_length=7),
        ),
    ]
