# Generated by Django 4.2.11 on 2024-09-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_note_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='toDo',
            new_name='to_do',
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('#EAEC40', 'Dandelion'), ('#FF7EB9', 'Pink'), ('#F275AD', 'Cyclamen'), ('#79CBC5', 'Pearl Aqua'), ('#FFFF97', 'Canary'), ('#7AFCFF', 'Blue'), ('#FBAE4A', 'Pastel Orange'), ('#F3858E', 'Tulip'), ('#B2EC5D', 'Inchworm'), ('#8D9440', 'Bright Green'), ('#FFFFFF', 'White'), ('#BEBEBE', 'Grey')], default='#F275AD', max_length=7),
        ),
    ]
