# Generated by Django 3.2.7 on 2024-09-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='photocard_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='vocab',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
