# Generated by Django 3.2.7 on 2024-10-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_note_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('#C0C0C0', 'Silver'), ('#8B5A2B', 'Sienna'), ('#3B444B', "Payne's Grey"), ('#FFDAB9', 'Peach Puff'), ('#FF6347', 'Tomato'), ('#FF69B4', 'Hot Pink'), ('#FF4500', 'Orange Red'), ('#FFFF66', 'Light Yellow'), ('#FFB6C1', 'Light Pink'), ('#8B4513', 'Saddle Brown'), ('#D2B48C', 'Tan'), ('#DEB887', 'Burly Wood'), ('#FF00FF', 'Magenta'), ('#00FFFF', 'Cyan'), ('#FFD700', 'Neon Gold'), ('#808080', 'Cool Grey'), ('#CD5C5C', 'Indian Red'), ('#4682B4', 'Steel Blue'), ('#000000', 'Black'), ('#FF0000', 'Red'), ('#0000FF', 'Royal Blue'), ('#228B22', 'Forest Green'), ('#FFA500', 'Orange'), ('#FF4500', 'Red Orange'), ('#9932CC', 'Dark Orchid'), ('#8B4513', 'Saddle Brown'), ('#FFD700', 'Gold'), ('#708090', 'Slate Grey'), ('#EAEC40', 'Dandelion'), ('#FF7EB9', 'Pink'), ('#F275AD', 'Cyclamen'), ('#79CBC5', 'Pearl Aqua'), ('#FFFF97', 'Canary'), ('#7AFCFF', 'Blue'), ('#FBAE4A', 'Pastel Orange'), ('#F3858E', 'Tulip'), ('#B2EC5D', 'Inchworm'), ('#8D9440', 'Bright Green'), ('#FFFFFF', 'White'), ('#BEBEBE', 'Grey')], default='#C0C0C0', max_length=7),
        ),
    ]
